// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEoPp_1LWISj0fHEAq-CvWXZJICq2JWDw',
    appId: '1:981184895290:android:6a47ad84591d5c0e789803',
    messagingSenderId: '981184895290',
    projectId: 'minimal-login-ui-884cd',
    databaseURL: 'https://minimal-login-ui-884cd-default-rtdb.firebaseio.com',
    storageBucket: 'minimal-login-ui-884cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwoxFjSISsxUEyH5xVV-0Gv2OkNizmWuY',
    appId: '1:981184895290:ios:355e13fb6f6f1948789803',
    messagingSenderId: '981184895290',
    projectId: 'minimal-login-ui-884cd',
    databaseURL: 'https://minimal-login-ui-884cd-default-rtdb.firebaseio.com',
    storageBucket: 'minimal-login-ui-884cd.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD43--9-bSi0blJAWvN5lL6kYD6EZOrgrs',
    appId: '1:981184895290:web:ea94abf3a6f41470789803',
    messagingSenderId: '981184895290',
    projectId: 'minimal-login-ui-884cd',
    authDomain: 'minimal-login-ui-884cd.firebaseapp.com',
    databaseURL: 'https://minimal-login-ui-884cd-default-rtdb.firebaseio.com',
    storageBucket: 'minimal-login-ui-884cd.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwoxFjSISsxUEyH5xVV-0Gv2OkNizmWuY',
    appId: '1:981184895290:ios:355e13fb6f6f1948789803',
    messagingSenderId: '981184895290',
    projectId: 'minimal-login-ui-884cd',
    databaseURL: 'https://minimal-login-ui-884cd-default-rtdb.firebaseio.com',
    storageBucket: 'minimal-login-ui-884cd.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD43--9-bSi0blJAWvN5lL6kYD6EZOrgrs',
    appId: '1:981184895290:web:ed76e4e293405310789803',
    messagingSenderId: '981184895290',
    projectId: 'minimal-login-ui-884cd',
    authDomain: 'minimal-login-ui-884cd.firebaseapp.com',
    databaseURL: 'https://minimal-login-ui-884cd-default-rtdb.firebaseio.com',
    storageBucket: 'minimal-login-ui-884cd.firebasestorage.app',
  );

}